package com.example.auto_ria.enums;

public enum EModel {
    TOYOTA_CAMRY(EBrand.TOYOTA),
    TOYOTA_COROLLA(EBrand.TOYOTA),
    TOYOTA_RAV4(EBrand.TOYOTA),
    TOYOTA_HIGHLANDER(EBrand.TOYOTA),
    TOYOTA_TACOMA(EBrand.TOYOTA),

    FORD_F150(EBrand.FORD),
    FORD_MUSTANG(EBrand.FORD),
    FORD_FOCUS(EBrand.FORD),
    FORD_ESCAPE(EBrand.FORD),
    FORD_EXPLORER(EBrand.FORD),

    CHEVROLET_SILVERADO(EBrand.CHEVROLET),
    CHEVROLET_CAMARO(EBrand.CHEVROLET),
    CHEVROLET_CRUZE(EBrand.CHEVROLET),
    CHEVROLET_TRAVERSE(EBrand.CHEVROLET),
    CHEVROLET_EQUINOX(EBrand.CHEVROLET),

    HONDA_CIVIC(EBrand.HONDA),
    HONDA_ACCORD(EBrand.HONDA),
    HONDA_CRV(EBrand.HONDA),
    HONDA_PILOT(EBrand.HONDA),
    HONDA_ODYSSEY(EBrand.HONDA),

    BMW_3_SERIES(EBrand.BMW),
    BMW_5_SERIES(EBrand.BMW),
    BMW_X3(EBrand.BMW),
    BMW_X5(EBrand.BMW),
    BMW_7_SERIES(EBrand.BMW),

    MERCEDES_C_CLASS(EBrand.MERCEDES),
    MERCEDES_E_CLASS(EBrand.MERCEDES),
    MERCEDES_GLE(EBrand.MERCEDES),
    MERCEDES_S_CLASS(EBrand.MERCEDES),
    MERCEDES_GLC(EBrand.MERCEDES),

    AUDI_A3(EBrand.AUDI),
    AUDI_A4(EBrand.AUDI),
    AUDI_A6(EBrand.AUDI),
    AUDI_Q5(EBrand.AUDI),
    AUDI_Q7(EBrand.AUDI),

    VOLKSWAGEN_GOLF(EBrand.VOLKSWAGEN),
    VOLKSWAGEN_JETTA(EBrand.VOLKSWAGEN),
    VOLKSWAGEN_PASSAT(EBrand.VOLKSWAGEN),
    VOLKSWAGEN_TIGUAN(EBrand.VOLKSWAGEN),
    VOLKSWAGEN_ATLAS(EBrand.VOLKSWAGEN),

    NISSAN_ALTIMA(EBrand.NISSAN),
    NISSAN_MAXIMA(EBrand.NISSAN),
    NISSAN_ROGUE(EBrand.NISSAN),
    NISSAN_PATHFINDER(EBrand.NISSAN),
    NISSAN_TITAN(EBrand.NISSAN),

    HYUNDAI_SONATA(EBrand.HYUNDAI),
    HYUNDAI_ELANTRA(EBrand.HYUNDAI),
    HYUNDAI_TUCSON(EBrand.HYUNDAI),
    HYUNDAI_SANTA_FE(EBrand.HYUNDAI),
    HYUNDAI_KONA(EBrand.HYUNDAI),

    KIA_OPTIMA(EBrand.KIA),
    KIA_SOUL(EBrand.KIA),
    KIA_SPORTAGE(EBrand.KIA),
    KIA_SORENTO(EBrand.KIA),
    KIA_TELLURIDE(EBrand.KIA),

    MAZDA_3(EBrand.MAZDA),
    MAZDA_6(EBrand.MAZDA),
    MAZDA_CX5(EBrand.MAZDA),
    MAZDA_CX9(EBrand.MAZDA),
    MAZDA_MX5(EBrand.MAZDA),

    SUBARU_IMPREZA(EBrand.SUBARU),
    SUBARU_OUTBACK(EBrand.SUBARU),
    SUBARU_FORESTER(EBrand.SUBARU),
    SUBARU_LEGACY(EBrand.SUBARU),
    SUBARU_CROSSTREK(EBrand.SUBARU),

    LEXUS_RX(EBrand.LEXUS),
    LEXUS_ES(EBrand.LEXUS),
    LEXUS_IS(EBrand.LEXUS),
    LEXUS_GX(EBrand.LEXUS),
    LEXUS_LX(EBrand.LEXUS),

    JEEP_WRANGLER(EBrand.JEEP),
    JEEP_GRAND_CHEROKEE(EBrand.JEEP),
    JEEP_COMPASS(EBrand.JEEP),
    JEEP_RENEGADE(EBrand.JEEP),
    JEEP_GLADIATOR(EBrand.JEEP),

    RAM_1500(EBrand.RAM),
    RAM_2500(EBrand.RAM),
    RAM_3500(EBrand.RAM),
    RAM_REBEL(EBrand.RAM),
    RAM_PROMASTER(EBrand.RAM),

    GMC_SIERRA(EBrand.GMC),
    GMC_YUKON(EBrand.GMC),
    GMC_ACADIA(EBrand.GMC),
    GMC_TERRAIN(EBrand.GMC),
    GMC_CANYON(EBrand.GMC),

    CADILLAC_ESCALADE(EBrand.CADILLAC),
    CADILLAC_CTS(EBrand.CADILLAC),
    CADILLAC_XT5(EBrand.CADILLAC),
    CADILLAC_XTS(EBrand.CADILLAC),
    CADILLAC_CT6(EBrand.CADILLAC),

    VOLVO_S60(EBrand.VOLVO),
    VOLVO_S90(EBrand.VOLVO),
    VOLVO_XC40(EBrand.VOLVO),
    VOLVO_XC60(EBrand.VOLVO),
    VOLVO_XC90(EBrand.VOLVO);

    private final EBrand brand;

    EModel(EBrand brand) {
        this.brand = brand;
    }

    public EBrand getBrand() {
        return brand;
    }
}
